print("+------+")
print("| Gage |")
print("+------+")

print("+------------------------------------------------+")
print("|    |                                           |")
print("|   -|          Hilyard, Gage                    |")
print("|  --|          Tribute Liabilities Associate    |")
print("| ---|          Parasail Capital                 |")
print("| ---------                                      |")
print("|  -------      4 Hunger Plaza                   |")
print("|               STE 1400                         |")
print("|               District 12, Panem 00012         |")
print("|                                                |")
print("| Work: (406) 373-3003  @: gage@parasail.com     |")
print("+------------------------------------------------+")
